name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Rust and musl-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential musl-tools rustup
        rustup default stable
        rustup component add clippy

  check-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check Formatting
      run: |
        cargo fmt --all -- --check && echo "Formatting check passed."

  test:
    needs: check-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Lint and Tests
      run: |
        cargo clippy --all-targets --all-features -- -D warnings
        cargo test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add musl Target
      run: |
        rustup target add x86_64-unknown-linux-musl

    - name: Build Static Binary
      run: |
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-genio-flash
        path: target/x86_64-unknown-linux-musl/release/debian-genio-flash
