# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Ignacy Kajdan <ignacy.kajdan@grinn-global.com>

name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Rust and musl-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential musl-tools rustup
        rustup default stable
        rustup component add clippy

  check-license:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Reuse
      run: pip install reuse

    - name: Run Reuse Lint
      run: reuse lint --lines && echo "License check passed."

  check-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check Formatting
      run: |
        cargo fmt --all -- --check && echo "Formatting check passed."

  check-deps:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install cargo-outdated
      run: cargo install cargo-outdated

    - name: Check for Outdated Dependencies
      run: cargo outdated
      continue-on-error: true

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run Cargo Audit
      run: cargo audit

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Lint and Tests
      run: |
        cargo test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add musl Target
      run: |
        rustup target add x86_64-unknown-linux-musl

    - name: Build Static Binary
      run: |
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-genio-flash
        path: target/x86_64-unknown-linux-musl/release/debian-genio-flash
