name: Build and Test the Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Build
      run: cargo build --release

    - name: Run Tests
      run: cargo test

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary
        path: target/release/grinn-flash
